# Generated by Django 6.1 on 2026-08-14 13:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_platform_cut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_publisher_cut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform revenue',
                'verbose_name_plural': 'platform revenue',
            },
        ),
        migrations.CreateModel(
            name='ContentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('publication', 'Publication / Article'), ('journal', 'Journal Issue'), ('thesis', 'Thesis / Dissertation')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'content price',
                'verbose_name_plural': 'content prices',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=12)),
                ('payment_details', models.TextField(blank=True, help_text='Bank/mobile money details')),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payout',
                'verbose_name_plural': 'payouts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('publisher_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publisher earnings',
                'verbose_name_plural': 'publisher earnings',
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('publication', 'Publication / Article'), ('journal', 'Journal Issue'), ('thesis', 'Thesis / Dissertation')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access grant',
                'verbose_name_plural': 'access grants',
                'unique_together': {('buyer', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publisher_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_ref', models.CharField(blank=True, max_length=200)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_notified', models.BooleanField(default=False)),
                ('publisher_notified', models.BooleanField(default=False)),
                ('owner_notified', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('content_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='payments.contentprice')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='payments_pu_buyer_i_666d2b_idx'), models.Index(fields=['status', '-created_at'], name='payments_pu_status_6b74fa_idx')],
            },
        ),
    ]
