services:
  - type: web
    name: gpas
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gpas-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SITE_URL
        value: "https://gpas.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://gpas.onrender.com"

databases:
  - name: gpas-db
    databaseName: gpas
    user: gpas
    plan: free