# Generated by Django 6.1 on 2026-08-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_banner', models.ImageField(blank=True, help_text='Homepage hero background image (recommended: 1920×900 px, JPG/PNG).', null=True, upload_to='site/banners/')),
                ('hero_title', models.CharField(blank=True, default='', help_text='Override hero headline text. Leave blank to use the default.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='', help_text='Override hero sub-heading. Leave blank to use the default.', max_length=300)),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo image (recommended: transparent PNG, ~200×60 px).', null=True, upload_to='site/logos/')),
                ('site_logo_white', models.ImageField(blank=True, help_text='White/inverted logo for dark navbar backgrounds.', null=True, upload_to='site/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (32×32 px ICO or PNG).', null=True, upload_to='site/logos/')),
                ('promo_image_1', models.ImageField(blank=True, help_text='Shown in the homepage features / about section.', null=True, upload_to='site/promo/', verbose_name='Promotional Image 1')),
                ('promo_image_2', models.ImageField(blank=True, null=True, upload_to='site/promo/', verbose_name='Promotional Image 2')),
                ('promo_image_3', models.ImageField(blank=True, null=True, upload_to='site/promo/', verbose_name='Promotional Image 3')),
                ('about_text', models.TextField(blank=True, default='', help_text='Short about-us text shown on the homepage.')),
                ('social_twitter', models.URLField(blank=True, default='', verbose_name='Twitter / X URL')),
                ('social_linkedin', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('social_facebook', models.URLField(blank=True, default='', verbose_name='Facebook URL')),
                ('social_youtube', models.URLField(blank=True, default='', verbose_name='YouTube URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
