# Generated by Django 6.1 on 2026-08-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('discipline', models.CharField(choices=[('nursing', 'Nursing'), ('medicine', 'Medicine'), ('midwifery', 'Midwifery'), ('pharmacy', 'Pharmacy'), ('dentistry', 'Dentistry'), ('public_health', 'Public Health'), ('biomedical', 'Biomedical Science'), ('allied_health', 'Allied Health Sciences')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='health_science.healthcategory')),
            ],
            options={
                'verbose_name_plural': 'Health Categories',
                'ordering': ['discipline', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=420, unique=True)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('textbook', 'Textbook'), ('paper', 'Research Paper'), ('guideline', 'Clinical Guideline'), ('lecture', 'Lecture Notes'), ('case_study', 'Case Study'), ('course', 'Course Material'), ('other', 'Other')], db_index=True, max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='health/resources/')),
                ('external_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='health_science.healthcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='health_scie_categor_fb8984_idx')],
            },
        ),
    ]
