# Generated by Django 6.1 on 2026-08-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('e_issn', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journals/covers/')),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('website', models.URLField(blank=True)),
                ('is_open_access', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField()),
                ('issue', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='publishing.journal')),
            ],
            options={
                'ordering': ['-year', '-volume', '-issue'],
                'unique_together': {('journal', 'volume', 'issue')},
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=520, unique=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('manuscript', models.FileField(blank=True, null=True, upload_to='publishing/manuscripts/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publishing/covers/')),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(default='English', max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'Editorial Screening'), ('under_review', 'Under Review'), ('revision_req', 'Revision Required'), ('final_review', 'Final Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_open_access', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publishing.journal')),
                ('journal_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publishing.journalissue')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
                ('pub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishing.publicationtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('screening_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='publishing.publication')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('revised_file', models.FileField(blank=True, null=True, upload_to='publishing/revisions/')),
                ('author_response', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_requests', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='publishing.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept'), ('minor', 'Minor Revision'), ('major', 'Major Revision'), ('reject', 'Reject')], max_length=10)),
                ('comments_to_author', models.TextField(blank=True)),
                ('comments_to_editor', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='publishing.submission')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/')),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='publishing__slug_767d2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_authors', to='publishing.publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('publication', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status', '-published_at'], name='publishing__status_909b06_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['slug'], name='publishing__slug_c03f57_idx'),
        ),
    ]
